# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import state_pb2 as state__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in state_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PredictionServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PredictState = channel.unary_unary(
                '/PredictionService/PredictState',
                request_serializer=state__pb2.PredictionRequest.SerializeToString,
                response_deserializer=state__pb2.PredictionResponse.FromString,
                _registered_method=True)


class PredictionServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def PredictState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PredictionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PredictState': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictState,
                    request_deserializer=state__pb2.PredictionRequest.FromString,
                    response_serializer=state__pb2.PredictionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'PredictionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('PredictionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PredictionService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PredictState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PredictionService/PredictState',
            state__pb2.PredictionRequest.SerializeToString,
            state__pb2.PredictionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ActionServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBestAction = channel.unary_unary(
                '/ActionService/GetBestAction',
                request_serializer=state__pb2.ActionRequest.SerializeToString,
                response_deserializer=state__pb2.ActionResponse.FromString,
                _registered_method=True)


class ActionServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetBestAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ActionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBestAction': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBestAction,
                    request_deserializer=state__pb2.ActionRequest.FromString,
                    response_serializer=state__pb2.ActionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ActionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ActionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ActionService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetBestAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ActionService/GetBestAction',
            state__pb2.ActionRequest.SerializeToString,
            state__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class KnowledgeServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.QueryCache = channel.unary_unary(
                '/KnowledgeService/QueryCache',
                request_serializer=state__pb2.CacheRequest.SerializeToString,
                response_deserializer=state__pb2.CacheResponse.FromString,
                _registered_method=True)
        self.StoreEntry = channel.unary_unary(
                '/KnowledgeService/StoreEntry',
                request_serializer=state__pb2.StoreRequest.SerializeToString,
                response_deserializer=state__pb2.StoreAck.FromString,
                _registered_method=True)
        self.SyncKnowledge = channel.stream_unary(
                '/KnowledgeService/SyncKnowledge',
                request_serializer=state__pb2.SyncUpdate.SerializeToString,
                response_deserializer=state__pb2.SyncAck.FromString,
                _registered_method=True)


class KnowledgeServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def QueryCache(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StoreEntry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncKnowledge(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KnowledgeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'QueryCache': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryCache,
                    request_deserializer=state__pb2.CacheRequest.FromString,
                    response_serializer=state__pb2.CacheResponse.SerializeToString,
            ),
            'StoreEntry': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreEntry,
                    request_deserializer=state__pb2.StoreRequest.FromString,
                    response_serializer=state__pb2.StoreAck.SerializeToString,
            ),
            'SyncKnowledge': grpc.stream_unary_rpc_method_handler(
                    servicer.SyncKnowledge,
                    request_deserializer=state__pb2.SyncUpdate.FromString,
                    response_serializer=state__pb2.SyncAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'KnowledgeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('KnowledgeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KnowledgeService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def QueryCache(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/KnowledgeService/QueryCache',
            state__pb2.CacheRequest.SerializeToString,
            state__pb2.CacheResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StoreEntry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/KnowledgeService/StoreEntry',
            state__pb2.StoreRequest.SerializeToString,
            state__pb2.StoreAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncKnowledge(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/KnowledgeService/SyncKnowledge',
            state__pb2.SyncUpdate.SerializeToString,
            state__pb2.SyncAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SyncServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.QueryAndSync = channel.unary_unary(
                '/SyncService/QueryAndSync',
                request_serializer=state__pb2.StateRequest.SerializeToString,
                response_deserializer=state__pb2.StateResponse.FromString,
                _registered_method=True)


class SyncServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def QueryAndSync(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SyncServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'QueryAndSync': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryAndSync,
                    request_deserializer=state__pb2.StateRequest.FromString,
                    response_serializer=state__pb2.StateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SyncService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('SyncService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SyncService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def QueryAndSync(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SyncService/QueryAndSync',
            state__pb2.StateRequest.SerializeToString,
            state__pb2.StateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
