# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: state.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'state.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bstate.proto\"/\n\x11PredictionRequest\x12\x1a\n\x12\x62\x61ndwidth_sequence\x18\x01 \x03(\x05\"C\n\x12PredictionResponse\x12\x17\n\x0fpredicted_state\x18\x01 \x01(\x05\x12\x14\n\x0cis_confident\x18\x02 \x01(\x08\"\x1e\n\rActionRequest\x12\r\n\x05state\x18\x01 \x01(\x05\"V\n\x0e\x41\x63tionResponse\x12\x13\n\x0b\x61\x63tion_name\x18\x01 \x01(\t\x12\x1b\n\x13\x65xpected_throughput\x18\x02 \x01(\x05\x12\x12\n\nis_optimal\x18\x03 \x01(\x08\"!\n\x0c\x43\x61\x63heRequest\x12\x11\n\tstate_key\x18\x01 \x01(\t\"F\n\rCacheResponse\x12\r\n\x05\x66ound\x18\x01 \x01(\x08\x12\x13\n\x0b\x61\x63tion_name\x18\x02 \x01(\t\x12\x11\n\tbandwidth\x18\x03 \x01(\x05\"I\n\x0cStoreRequest\x12\x11\n\tstate_key\x18\x01 \x01(\t\x12\x13\n\x0b\x61\x63tion_name\x18\x02 \x01(\t\x12\x11\n\tbandwidth\x18\x03 \x01(\x05\"\x1b\n\x08StoreAck\x12\x0f\n\x07success\x18\x01 \x01(\x08\"-\n\nSyncUpdate\x12\x1f\n\x05pairs\x18\x01 \x03(\x0b\x32\x10.StateActionPair\"C\n\x0fStateActionPair\x12\r\n\x05state\x18\x01 \x01(\x05\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\t\x12\x11\n\tbandwidth\x18\x03 \x01(\x05\" \n\x07SyncAck\x12\x15\n\rupdated_count\x18\x01 \x01(\x05\"-\n\x0cStateRequest\x12\r\n\x05state\x18\x01 \x01(\x05\x12\x0e\n\x06source\x18\x02 \x01(\t\"[\n\rStateResponse\x12\x13\n\x0b\x61\x63tion_name\x18\x01 \x01(\t\x12\x11\n\tbandwidth\x18\x02 \x01(\x05\x12\x12\n\nis_optimal\x18\x03 \x01(\x08\x12\x0e\n\x06source\x18\x04 \x01(\t2L\n\x11PredictionService\x12\x37\n\x0cPredictState\x12\x12.PredictionRequest\x1a\x13.PredictionResponse2A\n\rActionService\x12\x30\n\rGetBestAction\x12\x0e.ActionRequest\x1a\x0f.ActionResponse2\x91\x01\n\x10KnowledgeService\x12+\n\nQueryCache\x12\r.CacheRequest\x1a\x0e.CacheResponse\x12&\n\nStoreEntry\x12\r.StoreRequest\x1a\t.StoreAck\x12(\n\rSyncKnowledge\x12\x0b.SyncUpdate\x1a\x08.SyncAck(\x01\x32<\n\x0bSyncService\x12-\n\x0cQueryAndSync\x12\r.StateRequest\x1a\x0e.StateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'state_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PREDICTIONREQUEST']._serialized_start=15
  _globals['_PREDICTIONREQUEST']._serialized_end=62
  _globals['_PREDICTIONRESPONSE']._serialized_start=64
  _globals['_PREDICTIONRESPONSE']._serialized_end=131
  _globals['_ACTIONREQUEST']._serialized_start=133
  _globals['_ACTIONREQUEST']._serialized_end=163
  _globals['_ACTIONRESPONSE']._serialized_start=165
  _globals['_ACTIONRESPONSE']._serialized_end=251
  _globals['_CACHEREQUEST']._serialized_start=253
  _globals['_CACHEREQUEST']._serialized_end=286
  _globals['_CACHERESPONSE']._serialized_start=288
  _globals['_CACHERESPONSE']._serialized_end=358
  _globals['_STOREREQUEST']._serialized_start=360
  _globals['_STOREREQUEST']._serialized_end=433
  _globals['_STOREACK']._serialized_start=435
  _globals['_STOREACK']._serialized_end=462
  _globals['_SYNCUPDATE']._serialized_start=464
  _globals['_SYNCUPDATE']._serialized_end=509
  _globals['_STATEACTIONPAIR']._serialized_start=511
  _globals['_STATEACTIONPAIR']._serialized_end=578
  _globals['_SYNCACK']._serialized_start=580
  _globals['_SYNCACK']._serialized_end=612
  _globals['_STATEREQUEST']._serialized_start=614
  _globals['_STATEREQUEST']._serialized_end=659
  _globals['_STATERESPONSE']._serialized_start=661
  _globals['_STATERESPONSE']._serialized_end=752
  _globals['_PREDICTIONSERVICE']._serialized_start=754
  _globals['_PREDICTIONSERVICE']._serialized_end=830
  _globals['_ACTIONSERVICE']._serialized_start=832
  _globals['_ACTIONSERVICE']._serialized_end=897
  _globals['_KNOWLEDGESERVICE']._serialized_start=900
  _globals['_KNOWLEDGESERVICE']._serialized_end=1045
  _globals['_SYNCSERVICE']._serialized_start=1047
  _globals['_SYNCSERVICE']._serialized_end=1107
# @@protoc_insertion_point(module_scope)
